---

- set_fact: static_package_dir="{{ STATIC_SRC }}"

- shell: "cat {{ static_package_dir }}/package.json | jq -r '.devDependencies'"
  register: result

- set_fact: devDependencies="{{ result.stdout | from_json }}"

- name: Check Static Development Environment
  shell: "cat {{ static_package_dir }}/node_modules/{{ item.key }}/package.json | jq -r '.version'"
  with_dict: "{{ devDependencies }}"
  register: version_check
  changed_when: no
  failed_when: no

# - debug: var=version_check.results

- name: DEBUG01
  debug: msg= "{{ item }}"
  with_items: "{{ version_check }}"

- name: DEBUG02
  debug: msg= "{{ item }}"
  with_items: "{{ version_check.results }}"

# - name: DEBUG03
#   debug: msg= "{{ item }}"
#   with_dict: "{{ version_check.results }}"

# - name: Install Missing Static Development Libraries to Local Environment
#   npm: name="{{ item.item.key }}" version="{{ item.value }}" path="{{ static_package_dir }}" state=present
#   with_items: "{{  version_check.results }}"
#   when:
#     item.stdout == "" or (item.item.value != "*" and item.stdout != item.item.value)
